# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Apps by Alex Beaty
email: Mancala.Dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Showcase for my portfolio and service for the Apps that I build and maintain, such as <i>Mancala Fantasy - Online</i>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  jncosideout
github_url: https://github.com/jncosideout
senior_thesis: https://docs.google.com/document/d/1Pvsf8mkvSPBPWMvIS48InP2EKXXIy0nKCwXe14TLvbU/edit?usp=sharing
GnuPG_key: https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xd12087a83aa6e6d8

# additional Time Machine theme options
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]

collections:
  mancala:
    output: true

# blog settings
paginate: 2
#paginate_path: "/blog/page:num/"

# for menu items in header.html
# header_pages:
#   - about.md
#   - mancalaMain.html

# Build settings
theme: jekyll-theme-time-machine

plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "mancala"
    values:
      layout: "mancala"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Alex"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/img/GameCenter"
    values:
      family: "GameCenter"
  - scope:
      path: "assets/img/notifications"
    values:
      family: "notifications"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
